# *******************************************************************************************
#  File:  __init__.py
#
#  Created: 13-04-2022
#
#  Description: This file contains the system configuration
#
#  Copyright (c) 2022 James Dooley <james@dooley.ch>
#
#  History:
#  13-04-2022: Initial version
#
# *******************************************************************************************

[datamap_mysql]
tinyint = "int"
smallint = "int"
mediumint = "int"
int = "int"
bigint = "int"
decimal = "float"
float = "float"
double = "float"
date = "datetime"
datetime = "datetime"
timestamp = "datetime"
char = "str"
varchar = "str"
binary = "str"
varbinary = "str"
tinytext = "str"
text = "str"
mediumtext = "str"
longtext = "str"
enum = "str"
set = "str"
json = "str"

[explorer_plugins]

[explorer_plugins.mysql]
name = "mysql"
file = "mysql_explorer"

[generator_plugins]

[generator_plugins.python]
name = "python"
file = "python_code_generator"
